### ISSUE TITLE
0.42.4 .blitz folder not resolved by @next/stdlib with pnpm

### ISSUE THREAD

**Issue by 90dy** [blitz-js/blitz#2935]
### What is the problem?

When using blitz 0.42.4 (latest) with pnpm 6.16.0, .blitz folder is not resolved by @next/stdlib
It works with blitz 0.40.0

### Paste all your error logs here:

```
Uncaught TypeError: next_stdlib__WEBPACK_IMPORTED_MODULE_6__.Routes.SignupPage is not a function
    at UserInfo (index.tsx?39bb:38)
    at renderWithHooks (react-dom.development.js?bf59:15958)
    at mountIndeterminateComponent (react-dom.development.js?bf59:20783)
    at beginWork (react-dom.development.js?bf59:22270)
    at HTMLUnknownElement.callCallback (react-dom.development.js?bf59:4139)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?bf59:4188)
    at invokeGuardedCallback (react-dom.development.js?bf59:4252)
    at beginWork$1 (react-dom.development.js?bf59:26991)
    at performUnitOfWork (react-dom.development.js?bf59:26160)
    at workLoopConcurrent (react-dom.development.js?bf59:26146)
    at renderRootConcurrent (react-dom.development.js?bf59:26108)
    at performConcurrentWorkOnRoot (react-dom.development.js?bf59:25382)
    at workLoop (scheduler.development.js?4f06:256)
    at flushWork (scheduler.development.js?4f06:229)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?4f06:523)
UserInfo @ index.tsx?39bb:38
renderWithHooks @ react-dom.development.js?bf59:15958
mountIndeterminateComponent @ react-dom.development.js?bf59:20783
beginWork @ react-dom.development.js?bf59:22270
callCallback @ react-dom.development.js?bf59:4139
invokeGuardedCallbackDev @ react-dom.development.js?bf59:4188
invokeGuardedCallback @ react-dom.development.js?bf59:4252
beginWork$1 @ react-dom.development.js?bf59:26991
performUnitOfWork @ react-dom.development.js?bf59:26160
workLoopConcurrent @ react-dom.development.js?bf59:26146
renderRootConcurrent @ react-dom.development.js?bf59:26108
performConcurrentWorkOnRoot @ react-dom.development.js?bf59:25382
workLoop @ scheduler.development.js?4f06:256
flushWork @ scheduler.development.js?4f06:229
performWorkUntilDeadline @ scheduler.development.js?4f06:523
```

### Paste all relevant code snippets here:

```
PASTE_HERE (leave the ``` marks)
```

### What are detailed steps to reproduce this?

1. `blitz new apptest --pnpm --template=full --form=react-final-form --language=typescript`
2. `cd apptest`
3. `blitz dev`
4. `open http://localhost:3000

### Run `blitz -v` and paste the output here:

```
macOS Monterey | darwin-x64 | Node: v16.12.0

blitz: 0.42.4 (local)

  Package manager: npm 
  System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 595.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.12.0 - ~/.volta/tools/image/node/16.12.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 7.18.1 - ~/.volta/tools/image/npm/7.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @prisma/client: 3.4.2 => 3.4.2 
    blitz: 0.42.4 => 0.42.4 
    prisma: 3.4.2 => 3.4.2 
    react: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    react-dom: 18.0.0-alpha-5ca4b0433-20211020 => 18.0.0-alpha-5ca4b0433-20211020 
    typescript: ~4.4 => 4.4.4 ```


### Please include below any other applicable logs and screenshots that show your problem:

_No response_

**Comment by beerose** [comment]
Related issue: https://github.com/blitz-js/blitz/issues/2865

Does this happen only with pnpm?

**Comment by danestves** [comment]
Yeah, only with pnpm
