### ISSUE TITLE
(CLI version check error) Cannot find module create noop.js

### ISSUE THREAD

**Issue by DmacMcgreg** [blitz-js/blitz#3566]
### What is the problem?

blitz@alpha version 55 fails to create new project

### Paste all your error logs here:

```
➜  6_Code blitz new test-project
Error: Cannot find module 'blitz'
Require stack:
- /Users/d/Documents/6_Code/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/node_modules/resolve-from/index.js:46:47)
    at findNodeModulesRoot (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/dist/chunks/check-latest-version.cjs:34:10)
    at Object.checkLatestVersion (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/dist/chunks/check-latest-version.cjs:46:35)
    at async newApp (/Users/d/.nvm/versions/node/v16.13.0/lib/node_modules/blitz/dist/chunks/new.cjs:200:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/d/Documents/6_Code/noop.js' ]
}
```

### Paste all relevant code snippets here:

```
npm i -g blitz@alpha
blitz new test-project
```

### What are detailed steps to reproduce this?

1. npm i -g blitz@alpha
2. blitz new test-project
3. error

OR

1. npx blitz@alpha new test-project

### Run `blitz -v` and paste the output here:

```
➜  6_Code blitz -v
Blitz version: 2.0.0-alpha.55 (global)
macOS Monterey | darwin-x64 | Node: v16.13.0


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 278.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @blitzjs/auth: Not Found
    @blitzjs/next: Not Found
    @blitzjs/rpc: Not Found
    @prisma/client: Not Found
    blitz: Not Found
    next: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found

```

**Comment by freakaziod210** [comment]
Same same. I tried using yarn but that didn't work.

**Comment by Zeko369** [comment]
This is a bug with out update detection tool, in the meantime you can use `blitz new name --skip-upgrade`

**Comment by jmcelreavey** [comment]
> This is a bug with out update detection tool, in the meantime you can use `blitz new name --skip-upgrade`

Is there a solution currently for this that doesn't involve spinning up a new project? Some files I can modify locally?

**Comment by beerose** [comment]
Hey @jmcelreavey, this should be fixed in the newest alpha versions. Could you try with 2.0.0-alpha.63?

**Comment by jmcelreavey** [comment]
Yeah that did the trick! Thanks

**Comment by freakaziod210** [comment]
I also see this error when trying to installing a recipe.

**Comment by beerose** [comment]
> I also see this error when trying to installing a recipe.

Hey @freakaziod210! Recipes aren't currently working in Blitz 2.0.

**Comment by tommymarshall** [comment]
Seeing the same problem (unable to install recipes) with **2.0.0-beta.3**

Is it possible to have master be stable and leave alpha/beta versions as separate branches?

**Comment by DmacMcgreg** [comment]
➜  Improved git:(master) ✗ yarn export
yarn run v1.22.19
$ blitz export
Loaded env from /Users/d/Documents/6_Code/Lebri-Improved/.env.local
Loaded env from /Users/d/Documents/6_Code/Lebri-Improved/.env
Error: Cannot find module 'export'
Require stack:
- /Users/d/Documents/6_Code/Lebri-Improved/noop.js

@beerose  getting this with beta versions 

I've deleted node_modules and re-installed, I've tried 'npx blitz build' and 'npx blitz export' as well, same issue

**Comment by beerose** [comment]
@DmacMcgreg, we removed the `export` command in favor of `next export` (https://nextjs.org/docs/advanced-features/static-html-export). You can try running `next export` or `blitz next export `.

**Comment by beerose** [comment]
On second thought — we should add it back as we had additional `-o` and `-e` CLI options. We also still have this in the docs. Would you mind opening an issue for that, @DmacMcgreg?

**Comment by DmacMcgreg** [comment]
@beerose 
https://github.com/blitz-js/blitz/issues/3880

Cheers!

**Comment by kwekss** [comment]
Cannot find module 'expo/bin/cli.js'
Require stack:
- C:\Users\John\Documents\final year project\24\7-jobs\noop.js
Error: Cannot find module 'expo/bin/cli.js'
Require stack:
- C:\Users\John\Documents\final year project\24\7-jobs\noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at resolveFileName (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\node_modules\resolve-from\index.js:46:47)
    at installExpoUpdatesAsync (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\src\commands\publish\publishAsync.ts:167:34)
    at confirmExpoUpdatesInstalledAsync (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\src\commands\publish\publishAsync.ts:199:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at actionAsync (C:\Users\John\AppData\Roaming\npm\node_modules\expo-cli\src\commands\publish\publishAsync.ts:47:3)
