### ISSUE TITLE
Blitz export command is missing

### ISSUE THREAD

**Issue by DmacMcgreg** [blitz-js/blitz#3880]
### What is the problem?

When running blitz export, an error appears.

Probably we should put this command back?
Referencing: https://github.com/blitz-js/blitz/issues/3566#issuecomment-1264868614

### Paste all your error logs here:

```
➜ Improved git:(master) ✗ yarn export
yarn run v1.22.19
$ blitz export
Loaded env from /Users/d/Documents/6_Code/Lebri-Improved/.env.local
Loaded env from /Users/d/Documents/6_Code/Lebri-Improved/.env
Error: Cannot find module 'export'
Require stack:

/Users/d/Documents/6_Code/Improved/noop.js

```

### Paste all relevant code snippets here:

See above

### What are detailed steps to reproduce this?

1. blitz export

### Run `blitz -v` and paste the output here:

```
blitz beta 
```

**Comment by estevanjantsk** [comment]
I will try to work on this one 👍

**Comment by estevanjantsk** [comment]
@beerose could you provide me the PR where this cmd was removed, please? 🤔 I tried but I didn't find.

**Comment by beerose** [comment]
> @beerose could you provide me the PR where this cmd was removed, please? 🤔 I tried but I didn't find.

@estevanjantsk Actually, it was never _removed_ per se — it was never _added_. We had it in Blitz 1.0, and then when we started working on Blitz 2.0 it was from ground zero. We were moving some things from old Blitz to new Blitz, but a few stuff got missed. Export command was one of them. Here's the code that should be added back to this repo: https://github.com/blitz-js/legacy-framework/blob/main/packages/cli/src/commands/export.ts

**Comment by estevanjantsk** [comment]
YAS, ready to be reviewed.
