### ISSUE TITLE
Cannot find module .next/server/blitz-db.js on Vercel deployment

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2477]
### What is the problem?

After upgrading from 0.36.3 to 0.37.0 my Vercel deployment builds successfully but there are server errors when trying to log in to the app. When I roll back to 0.36.3 login works fine.

### Paste all your error logs here:

```
2021-06-11 15:36:55.336 ERROR login() 
 Error  Cannot find module '/var/task/packages/website/.next/server/blitz-db.js'
Require stack:
- /var/task/packages/website/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js
- /var/task/packages/website/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js
- /var/task/packages/website/.next/serverless/pages/api/auth/queries/getCurrentUser.js
- /var/task/packages/website/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
details:
{
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/packages/website/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js',
    '/var/task/packages/website/node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.js',
    '/var/task/packages/website/.next/serverless/pages/api/auth/queries/getCurrentUser.js',
    '/var/task/packages/website/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
error stack:
• blitzjs-core-server.cjs.prod.js:500 getDb
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:500:25
• blitzjs-core-server.cjs.prod.js:510 getSession
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:510:12
• blitzjs-core-server.cjs.prod.js:1172 createNewSession
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1172:48
• blitzjs-core-server.cjs.prod.js:745 $create
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:745:26
• 4490.js:90 login
    .next/serverless/chunks/4490.js:90:21
• blitzjs-core-server.cjs.prod.js:1604 <anonymous>
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1604:22
```

### Paste all relevant code snippets here:

n/a

### What are detailed steps to reproduce this?

n/a

### Run `blitz -v` and paste the output here:

```
Windows 10 | win32-x64 | Node: v14.15.5

blitz: 0.34.3 (global)
blitz: 0.37.0 (local) 

  Package manager: npm
  System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 8.60 GB / 15.94 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.37.0 => 0.37.0
    prisma: 2.24.1 => 2.24.1
    react: 0.0.0-experimental-6a589ad71 => 18.0.0-alpha-e6be2d531
    react-dom: 0.0.0-experimental-6a589ad71 => 18.0.0-alpha-e6be2d531
    typescript: ~4.2 => 4.2.4
```

**Comment by flybayer** [comment]
Sorry about that. I definitely tested this before release and it was working. But I can reproduce your problem. So looking into it.
