### ISSUE TITLE
0.38.0 errors: Can't resolve 'fs' and Cannot find module 'build-manifest.json'

### ISSUE THREAD

**Issue by acornellier** [blitz-js/blitz#2500]
### What is the problem?

After upgrading from 0.36.4 to 0.38.0, I get two errors when running the app. I didn't see these errors in 0.37.0 either.
I tried clearing .next, .blitz, and node_modules.

### Paste all your error logs here:

```
error - ../../node_modules/@blitzjs/core/server/dist/blitzjs-core-server.esm.js:6:0
Module not found: Can't resolve 'fs'
null
```

```
Error: Cannot find module '/Users/acornellier/git/Leaflet/.next/build-manifest.json'
Require stack:
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/api-utils.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/server/next.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/server/lib/start-server.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/cli/next-dev.js
- /Users/acornellier/git/Leaflet/node_modules/next/dist/bin/next
- /Users/acornellier/git/Leaflet/node_modules/@blitzjs/server/bin/next-patched
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.mod._resolveFilename (/Users/acornellier/git/Leaflet/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadComponents (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js:1:1557)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DevServer.findPageComponents (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js:77:257)
    at async DevServer.renderErrorToHTML (/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js:139:266) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/load-components.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/api-utils.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/next-server/server/next-server.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/server/next.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/server/lib/start-server.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/cli/next-dev.js',
    '/Users/acornellier/git/Leaflet/node_modules/next/dist/bin/next',
    '/Users/acornellier/git/Leaflet/node_modules/@blitzjs/server/bin/next-patched'
  ]
}
```

### Paste all relevant code snippets here:

blitz.config.ts
```ts
import type { BlitzConfig } from "blitz"
import type { Ctx } from "@blitzjs/core/dist/declarations/types"
import type { ImageConfig } from "next/dist/next-server/server/image-config"
import { sessionMiddleware } from "blitz"

const isAuthorized = ({ ctx: { session }, args }: { ctx: Ctx; args: any }) => {
  const requirements = args[0]
  if (!requirements) return true

  const { roles: requiredRoles, userId: requiredUserId } = requirements

  if (
    requiredRoles &&
    !session.roles!.some((role) => requiredRoles.includes(role))
  ) {
    return false
  }

  if (
    requiredUserId !== undefined &&
    session.userId !== requiredUserId &&
    !(session.adminMode && session.roles!.some((role) => role === `ADMIN`))
  ) {
    return false
  }

  return true
}

const withBundleAnalyzer = require(`@next/bundle-analyzer`)({
  enabled: process.env.ANALYZE === `true`,
})

const config: BlitzConfig & { images: Partial<ImageConfig> } = {
  experimental: {
    reactRoot: false,
  },
  middleware: [
    sessionMiddleware({
      isAuthorized,
    }),
  ],
  images: {
    domains: [`storage.googleapis.com`, `cdn.fakercloud.com`],
  },
  // eslint-disable-next-line require-await
  async headers() {
    return [
      {
        source: `/:all*(svg|jpg|png|gif)`,
        locale: false,
        headers: [
          {
            key: `Cache-Control`,
            value: `public, max-age=9999999999, must-revalidate`,
          },
        ],
      },
    ]
  },
}

module.exports = withBundleAnalyzer(config)
```

### What are detailed steps to reproduce this?

unsure how to reproduce outside my app

### Run `blitz -v` and paste the output here:

```
macOS Big Sur | darwin-x64 | Node: v14.16.1

blitz: 0.38.0 (global)
blitz: 0.38.0 (local)

  Package manager: yarn
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 641.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/node
    Yarn: 1.22.10 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/yarn
    npm: 7.12.0 - /var/folders/6f/xtx4d86j6vz71z0cdx3kt3400000gq/T/fnm_multishells/905_1623504293574/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.38.0 => 0.38.0
    prisma: 2.25.0 => 2.25.0
    react: alpha => 18.0.0-alpha-43f4cc160
    react-dom: alpha => 18.0.0-alpha-43f4cc160
    typescript: 4.3.3 => 4.3.3
```

**Comment by flybayer** [comment]
Does that happen with `blitz dev` or `blitz build` or both?

**Comment by acornellier** [comment]
@flybayer both

**Comment by acornellier** [comment]
@flybayer both

**Comment by acornellier** [comment]
any tips on how I could debug this @flybayer ?

**Comment by flybayer** [comment]
@acornellier I would start deleting code files to try to track down where the issue is. Like for example if you delete all pages but one, does it still fail?

**Comment by kivi** [comment]
Hi @acornellier,

I had a similar problem in previous Blitz versions and after updating from 0.37 to 0.38 I have similar error messages.

Try what I did in `blitz.config.ts`

Add a `webpack` config to your `module.exports`

```
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    config.resolve.fallback = {
      ...config.resolve.fallback,
      fs: false,
    }
    return config
  },
```

**Comment by acornellier** [comment]
@kivi then I just get
```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].resolve has an unknown property 'fallback'. 
 ```

**Comment by acornellier** [comment]
@kivi Indeed, that solved the errors I was getting! thanks

Now I'm getting another strange error though...
```
warn  - ../../node_modules/next/dist/next-server/server/load-components.js
Critical dependency: the request of a dependency is an expression
```

Maybe I'll make a separate issue for it

**Comment by acornellier** [comment]
OK, no idea how I fixed this honestly, I was just deleting code until it eventually worked, then I brought the code back and it continued to work. For anybody else this happens to, I recommend doing a full wipe - re-clone your repo.

**Comment by flybayer** [comment]
@kivi @acornellier the webpack `fs: false` thing is sort of like a band-aid. It's just covering up some other problem.

One case where `can't resolve fs` occurs is if you import something with server code into your frontend. Then only thing you can do this with is query/mutation resolvers.

**Comment by kivi** [comment]
@flybayer indeed, it is a band-aid. In my case, I have a `herlper.ts`, which imports `fs` and that just for a function used server side only. I don't need `fs` on client, but I use `helper.ts` in some `tsx` files. I could simply structure my code and I won't get that error described here even without the "band-aid"

**Comment by flybayer** [comment]
Ok that makes perfect sense.

Then I'm going to close this unless someone finds we do have a bug in our code/build process.

**Comment by maotora** [comment]
@kivi I get this error when I use your solution

```
> Build error occurred
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
   -> Options for the resolver
 - configuration[1].resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }

```

**Comment by kivi** [comment]
@maotora it is rather a workaround and not a solution.
I suggest you try to find where you use fs and see if you can only import it conditionally only on server side...
