### ISSUE TITLE
Ctx from blitz isn't overridden correctly by blitzjs/auth causing TS errors in > alpha.50

### ISSUE THREAD

**Issue by lhocke** [blitz-js/blitz#3519]
### What is the problem?

upgrading to blitz@alpha.50 and above introduces errors in tsc which prevent production build seemingly related to using a zod validation in resolver, both importing from a validations file and declaring within a mutation.

Note: blitz -v shows ```Blitz version: 2.0.0-alpha.50 (local)``` for this report but issues persists up to 2.00-alpha.53 (the latest version as of this post)

### Paste all your error logs here:

```
app/auth/mutations/changePassword.ts:9:16 - error TS2345: Argument of type 'ZodObject<{ currentPassword: ZodString; newPassword: ZodEffects<ZodString, string, string>; }, "strip", ZodTypeAny, { currentPassword: string; newPassword: string; }, { ...; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Type 'ZodObject<{ currentPassword: ZodString; newPassword: ZodEffects<ZodString, string, string>; }, "strip", ZodTypeAny, { currentPassword: string; newPassword: string; }, { ...; }>' is missing the following properties from type 'ZodType<any, any, any>': description, _getType, _getOrReturnCtx, describe

9   resolver.zod(ChangePassword),
                 ~~~~~~~~~~~~~~

app/auth/mutations/forgotPassword.ts:9:43 - error TS2345: Argument of type 'ZodObject<{ email: ZodEffects<ZodString, string, string>; orgId: ZodNumber; }, "strip", ZodTypeAny, { orgId: number; email: string; }, { orgId: number; email: string; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Type 'ZodObject<{ email: ZodEffects<ZodString, string, string>; orgId: ZodNumber; }, "strip", ZodTypeAny, { orgId: number; email: string; }, { orgId: number; email: string; }>' is missing the following properties from type 'ZodType<any, any, any>': description, _getType, _getOrReturnCtx, describe

9 export default resolver.pipe(resolver.zod(ForgotPassword), async ({ email, orgId }, ctx) => {
                                            ~~~~~~~~~~~~~~

app/auth/mutations/impersonateUser.ts:10:16 - error TS2345: Argument of type 'ZodObject<{ memberId: ZodString; }, "strip", ZodTypeAny, { memberId: string; }, { memberId: string; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Type 'ZodObject<{ memberId: ZodString; }, "strip", ZodTypeAny, { memberId: string; }, { memberId: string; }>' is missing the following properties from type 'ZodType<any, any, any>': description, _getType, _getOrReturnCtx, describe

10   resolver.zod(ImpersonateUserInput),
                  ~~~~~~~~~~~~~~~~~~~~

app/auth/mutations/login.ts:32:43 - error TS2345: Argument of type 'ZodObject<{ username: ZodEffects<ZodString, string, string>; password: ZodString; orgId: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>' is not assignable to parameter of type 'ZodTypeAny'.
  Type 'ZodObject<{ username: ZodEffects<ZodString, string, string>; password: ZodString; orgId: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>' is missing the following properties from type 'ZodType<any, any, any>': description, _getType, _getOrReturnCtx, describe

32 export default resolver.pipe(resolver.zod(Login), async ({ username, password, orgId }, ctx) => {
                                             ~~~~~


Found 4 errors in 4 files.

Errors  Files
     1  app/auth/mutations/changePassword.ts:9
     1  app/auth/mutations/forgotPassword.ts:9
     1  app/auth/mutations/impersonateUser.ts:10
     1  app/auth/mutations/login.ts:32

```

### Paste all relevant code snippets here:

```
// app/auth/validations
import { z } from "zod"

export const email = z
  .string()
  .email()
  .transform((str) => str.toLowerCase().trim())

export const password = z
  .string()
  .min(10)
  .max(100)
  .transform((str) => str.trim())

export const username = z
  .string()
  .min(5)
  .max(32)
  .transform((str) => str.toLowerCase().trim())

export const orgId = z.
  number()

export const Signup = z.object({
  username,
  email,
  password,
  orgId
})

export const Login = z.object({
  username,
  password: z.string(),
  orgId,
})

export const ForgotPassword = z.object({
  email,
  orgId
})

export const ResetPassword = z
  .object({
    password: password,
    passwordConfirmation: password,
    token: z.string(),
  })
  .refine((data) => data.password === data.passwordConfirmation, {
    message: "Passwords don't match",
    path: ["passwordConfirmation"], // set the path of the error
  })

export const ChangePassword = z.object({
  currentPassword: z.string(),
  newPassword: password,
})


// app/auth/mutations/changePassword.ts
import { ChangePassword } from "../validations"
...
resolver.pipe(
  resolver.zod(ChangePassword),
  resolver.authorize(),
  async ({ currentPassword, newPassword }, ctx) => {...})

// app/auth/mutations/forgotPassword.ts
import { ForgotPassword } from "../validations"
...
export default resolver.pipe(resolver.zod(ForgotPassword), async ({ email, orgId }, ctx) => {...})

// app/auth/mutations/impersonateUser.ts
export const ImpersonateUserInput = z.object({
  memberId: z.string()
})
...
export default resolver.pipe(resolver.zod(ImpersonateUserInput), resolver.authorize(), async ({ memberId }, ctx) => {...})

// app/auth/mutations/login.ts
import { Login } from "../validations"
...
export default resolver.pipe(resolver.zod(Login), async ({ username, password, orgId }, ctx) => {...})
```

### What are detailed steps to reproduce this?

1. update blitz to blitz@alpha
2. run npx tsc

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-alpha.53 (global)
Blitz version: 2.0.0-alpha.50 (local)
macOS Monterey | darwin-x64 | Node: v18.0.0


 Package manager: npm

  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.71 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.10.0 - /usr/local/bin/npm
  npmPackages:
    @prisma/client: 4.0.0 => 4.0.0 
    blitz: 2.0.0-alpha.50 => 2.0.0-alpha.50 
    next: >=12.2.1 => 12.2.1 
    prisma: 4.0.0 => 4.0.0 
    react: 18.0.0 => 18.0.0 
    react-dom: 18.0.0 => 18.0.0 
    typescript: >=4.7.4 => 4.7.4 
```

**Comment by Zeko369** [comment]
That's a weird bug with zod versioning (although not SEMVER incompatible it was incompatible with blitz), we ran into the similar thing trying to run alpha.45 with latest zod.

Just run `yarn add zod@latest` and it should work

**Comment by lhocke** [comment]
huh, interesting. after updating zod and bringing blitz to 2.0.0-alpha-53 (same with @blitjs/auth, @blitzjs/rpc, and @blitzjs/next) tsc now throws
```
app/auth/mutations/login.ts:37:50 - error TS2345: Argument of type '{ userId: string; role: Role; orgId: number; }' is not assignable to parameter of type '{ userId: unknown; }'.
  Object literal may only specify known properties, and 'role' does not exist in type '{ userId: unknown; }'.

37   await ctx.session.$create({ userId: member.id, role: member.role as Role, orgId: member.orgId})
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~

app/posts/mutations/updatePost.ts:9:54 - error TS2304: Cannot find name 'Ctx'.

9 export default async function UpdatePost(input, ctx: Ctx) {
                                                       ~~~

app/posts/mutations/updatePost.ts:14:64 - error TS2345: Argument of type '{ where: { id: any; }; input: any; }' is not assignable to parameter of type '{ select?: PostSelect | null | undefined; include?: PostInclude | null | undefined; data: (Without<PostUpdateInput, PostUncheckedUpdateInput> & PostUncheckedUpdateInput) | (Without<...> & PostUpdateInput); where: PostWhereUniqueInput; }'.
  Object literal may only specify known properties, and 'input' does not exist in type '{ select?: PostSelect | null | undefined; include?: PostInclude | null | undefined; data: (Without<PostUpdateInput, PostUncheckedUpdateInput> & PostUncheckedUpdateInput) | (Without<...> & PostUpdateInput); where: PostWhereUniqueInput; }'.

14   const post = await db.post.update({ where: { id: input.id }, input });
                                                                  ~~~~~

app/users/queries/getCurrentUser.ts:8:14 - error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.

8     where: { id: session.userId },
               ~~

  node_modules/.prisma/client/index.d.ts:18868:5
    18868     id?: string
              ~~
    The expected type comes from property 'id' which is declared here on type 'MembershipWhereUniqueInput'

pages/admin/index.tsx:13:19 - error TS2339: Property 'role' does not exist on type 'SessionContext'.

13   if (ctx.session.role == "ADMIN") {
                     ~~~~

pages/blog/new.tsx:13:19 - error TS2339: Property 'role' does not exist on type 'SessionContext'.

13   if (ctx.session.role == "ADMIN") {
                     ~~~~

pages/blog/new.tsx:36:45 - error TS2322: Type 'string | null' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.

36         initialValues={{title:"", body: "", author: session.userId}}
                                               ~~~~~~
```

**Comment by Zeko369** [comment]
It looks like your `Ctx` type isn't setup correctly. Could you paste it here (types.ts file should have it)

**Comment by lhocke** [comment]
I've really only slightly modified types.ts so that roles are of type enum in a postgres database and added impersonatingFrom, haven't explicitly changed Ctx at all. Pasted the entire file below.

```
import { SimpleRolesIsAuthorized } from "@blitzjs/auth"
import { Membership, Role } from "db"

// export type Role = "ADMIN" | "USER"

declare module "@blitzjs/auth" {
  export interface Session {
    isAuthorized: SimpleRolesIsAuthorized<Role>
    PublicData: {
      userId: Membership["id"]
      role: Membership["role"]
      orgId: number
      impersonatingFromUserId?: string
      impersonatingFromOrgId?: number
    }
  }
}
```

**Comment by lhocke** [comment]
okay, resolved this error
```
app/posts/mutations/updatePost.ts:9:54 - error TS2304: Cannot find name 'Ctx'.

9 export default async function UpdatePost(input, ctx: Ctx) {
```

the generator hadn't imported Ctx from blitz on the mutation, the other errors remain

**Comment by Zeko369** [comment]
@lhocke Does adding this to the `types.ts` fix it (and importing `SessionContext` from `@blitzjs/auth`)

```ts
declare module "blitz" {
  export interface Ctx {
    session: SessionContext
  }
}
```

**Comment by lhocke** [comment]
that does indeed

**Comment by Zeko369** [comment]
@lhocke figured out the problem, you probably have the same on, try pinning all `@blitz/package` to the same version `2.0.0-alpha.53`. I had all of them on `alpha` and for some reason one of them was pulled as an old version and that's why it wasn't working

**Comment by Zeko369** [comment]
Yup, glad we fixed it

<img width="847" alt="image" src="https://user-images.githubusercontent.com/3064377/177963688-3c759717-e889-4116-a5dc-f396ed2c8d08.png">

**Comment by dillonraphael** [comment]
Ya sorry about the inconsistent tags. We'll be doing a proper release outside of prerlease mode for the beta which will keep things consistent from there. I'll close this issue since it seems to be figured out.
