### ISSUE TITLE
Upgrading to 0.15.1 breaks `blitz start` for existing projects. @blitzjs/cli: Cannot find module 'react'

### ISSUE THREAD

**Issue by simonedelmann** [blitz-js/blitz#699]
### What is the problem?

When I upgraded to 0.15.1 (from 0.14.0), `blitz start` stops working and only shows a big error.

<details>
  <summary>Error Message</summary>

```
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/build.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/db.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/console.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/db.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) [MODULE_NOT_FOUND] Error Plugin: @blitzjs/cli: Cannot find module 'react'
Require stack:
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/dist/react-query.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/react-query/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/core.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/core/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/server.cjs.development.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/server/dist/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/commands/start.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/config.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/config/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/command.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@oclif/command/lib/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/dist/cli.js
module: @oclif/config@1.15.1
task: toCached
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
(node:9456) TypeError Plugin: @blitzjs/cli: Cannot read property 'dim' of undefined
module: @oclif/config@1.15.1
task: runHook command_not_found
plugin: @blitzjs/cli
root: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli
See more details with DEBUG=*
 ›   Error: command start not found
```  
</details>

This only happens if the blitz project is based on npm (`package-lock.json`) and not yarn (`yarn.lock`).

### Steps to Reproduce

1. Make sure yarn is **not** installed
2. Update to last version (0.15.1) of blitz: `npm install -g blitz`
3. Create new project `blitz new foo; cd foo`
4. Try to start the server `blitz start`

### Versions

```
debug: global
debug: pkgPath: /Users/simon/.fnm/node-versions/v14.4.0/installation/lib/node_modules/blitz/node_modules/@blitzjs/cli/lib/src/index.js 

macOS Catalina | darwin-x64 | Node: v14.4.0

blitz: 0.15.1 (global)
```

Edit: This also happens on 0.15.0, but **not** on 0.14.2-canary.0, so the error has to be https://github.com/blitz-js/blitz/compare/v0.14.2-canary.0...v0.15.0

**Comment by simonedelmann** [comment]
### Workaround

As workaround install react globally via `npm install -g react` or downgrade to 0.14.0 `npm install -g blitz@0.14.0`.

**Comment by simonedelmann** [comment]
Some more research:
- React was not installed globally before 0.15.0, so for some reasons 0.15.0 does require react, while 0.14.0 does not. 
- Looking at all changes made with 0.15.0 there is only one change related to react: The file `/packages/core/src/with-router.tsx` is created. https://github.com/blitz-js/blitz/blob/canary/packages/core/src/with-router.tsx
- This file imports react (`import React from 'react'`) for using `React.ComponentType` and `React.FC`

**Comment by flybayer** [comment]
@simonedelmann thank you for all the extra debugging information!!

---

I think the solution would be to destructure that React import, like this:

```tsx
import {FC, ComponentType} from 'react'
```

**Comment by simonedelmann** [comment]
@flybayer I changed the react import. Unfortunately I cannot test right now if that fixes the issue.
https://github.com/simonedelmann/blitz/tree/fix-react-import
Anyone feel free to add a PR!

**Comment by miguelalche** [comment]
Testing it right now

**Comment by miguelalche** [comment]
It seems that only doing this
```
import {FC, ComponentType} from 'react'
```
Doesn't work since we need react to be imported because there is a JSX tag in the file. 

Also I realized I didn't know how to test this was working, because doing 
```
yarn link-cli
```
and then executing yarn blitz new app without any changes didn't throw the error (while it did throw the error when I tried to run blitz for the first time )
