### ISSUE TITLE
cli: `blitz install` installs recipes

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#3253]

**Comment by markdav** [comment]
Hey there,  not much of a description - is this issue to get the recipe install working on the 2.0 version?  Just trying out blitz for the first time and the recipe install command doesn't seem to work per the [documentation](https://blitzjs.com/docs/why-blitz#5-recipes):

```bash
$ blitz install material-ui
Loaded env from C:\Users\markdav\code\trackShack\.env.local
Loaded env from C:\Users\markdav\code\trackShack\.env
Error: Cannot find module 'install'
Require stack:
- C:\Users\markdav\code\trackShack\noop.js

$ blitz --version
Loaded env from C:\Users\markdav\code\trackShack\.env.local
Loaded env from C:\Users\markdav\code\trackShack\.env
Blitz version: 2.0.0-alpha.57 (global)
Blitz version: 2.0.0-alpha.57 (local)
Windows 10 | win32-x64 | Node: v16.15.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 17.16 GB / 31.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: alpha => 2.0.0-alpha.57
    @blitzjs/next: alpha => 2.0.0-alpha.57
    @blitzjs/rpc: alpha => 2.0.0-alpha.57
    @prisma/client: 3.9.0 => 3.9.0
    blitz: 2.0.0-alpha.57 => 2.0.0-alpha.57
    next: 12.2.0 => 12.2.0
    prisma: 4.0.0 => 4.0.0
    react: 18.0.0 => 18.0.0
    react-dom: 18.0.0 => 18.0.0
    typescript: ^4.5.3 => 4.7.4

```

**Comment by markdav** [comment]
Okay - I just noticed that I'm using 2.0.0-alpha which is apparently fairly early days at the moment and I guess not full-featured.

**Comment by beerose** [comment]
> Okay - I just noticed that I'm using 2.0.0-alpha which is apparently fairly early days at the moment and I guess not full-featured.

Yep — the `blitz install` command is not yet supported.

**Comment by aaly00** [comment]
What would be the recommended way to install material ui without recipes ?

**Comment by noxify** [comment]
@aaly00 - i would assume, the current workaround is to use the material ui example for nextjs and check what they did to add add material ui to nextjs :)

https://github.com/mui/material-ui/tree/master/examples/nextjs-with-typescript

**Comment by aaly00** [comment]
Thanks! That's what I assumed 👍

**Comment by DataCrusade1999** [comment]
> What would be the recommended way to install material UI without recipes?

This is what I would recommend because I wanted to install tailwind but I couldn't and then I asked around on Discussion.

- [Here's the link to the Discussion](https://github.com/blitz-js/blitz/discussions/3757)

- [Material UI recipe from legacy framework](https://github.com/blitz-js/legacy-framework/tree/main/recipes/material-ui)

If you had installed material UI previously then you probably know where you have to create certain files.

- [otherwise, look at line 189](https://github.com/blitz-js/legacy-framework/blob/main/recipes/material-ui/index.ts)

- Remember you do have to install all your dependencies manually listed here from [lines 17 to 21](https://github.com/blitz-js/legacy-framework/blob/main/recipes/material-ui/index.ts#L17)
