### ISSUE TITLE
Error: Cannot find module 'next/constants'

### ISSUE THREAD

**Issue by paulm17** [blitz-js/blitz#2195]
### What is the problem?

Since upgrading to 0.34.0-canary.2, whenever I am interacting with NPM and running blitz dev.  I get a cannot find module with 'next/constants'

### Paste all your error logs here:

```
Error: Cannot find module 'next/constants'
Require stack:
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.js
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/display/dist/blitzjs-display.cjs.dev.js
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/display/dist/blitzjs-display.cjs.js
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/cli/lib/src/commands/db.js
- /Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/plugin.js
- /Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/config.js
- /Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/index.js
- /Users/paul/Share/development/[project]/node_modules/@oclif/command/lib/command.js
- /Users/paul/Share/development/[project]/node_modules/@oclif/command/lib/index.js
- /Users/paul/Share/development/[project]/node_modules/@blitzjs/cli/lib/src/index.js
- /Users/paul/.nvm/versions/node/v14.15.4/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js
- /Users/paul/.nvm/versions/node/v14.15.4/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Module._load (internal/modules/cjs/loader.js:725:27)
    at Function._load (/Users/paul/Share/development/[project]/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/paul/Share/development/[project]/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at getConfig (/Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js:46:18)
    at Dev.<anonymous> (/Users/paul/Share/development/[project]/node_modules/@blitzjs/cli/lib/src/commands/dev.js:22:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/paul/Share/development/[project]/node_modules/tslib/tslib.js:114:62) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.dev.js',
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/config/dist/blitzjs-config.cjs.js',
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/display/dist/blitzjs-display.cjs.dev.js',
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/display/dist/blitzjs-display.cjs.js',
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/cli/lib/src/commands/db.js',
    '/Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/plugin.js',
    '/Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/config.js',
    '/Users/paul/Share/development/[project]/node_modules/@oclif/config/lib/index.js',
    '/Users/paul/Share/development/[project]/node_modules/@oclif/command/lib/command.js',
    '/Users/paul/Share/development/[project]/node_modules/@oclif/command/lib/index.js',
    '/Users/paul/Share/development/[project]/node_modules/@blitzjs/cli/lib/src/index.js',
    '/Users/paul/.nvm/versions/node/v14.15.4/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.dev.js',
    '/Users/paul/.nvm/versions/node/v14.15.4/lib/node_modules/blitz/cli/dist/blitz-cli.cjs.js'
  ]
}
```

### Paste all relevant code snippets here:

.

### What are detailed steps to reproduce this?

1.

### Run `blitz -v` and paste the output here:

```
macOS Mojave | darwin-x64 | Node: v14.15.4

blitz: 0.34.0-canary.2 (global)
blitz: 0.34.0-canary.2 (local)

  Package manager: npm
  System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 160.23 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: Not Found
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1
    blitz: 0.34.0-canary.2 => 0.34.0-canary.2
    prisma: ~2.20 => 2.20.1
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71
    typescript: ~4.2 => 4.2.4
```

**Comment by wescopeland** [comment]
I am experiencing the same since using `canary.2`. Based on nothing, I suspect this is also the cause of https://github.com/blitz-js/blitz/issues/2192.

**Comment by flybayer** [comment]
Thanks y'all, will try to find a fix. I think a workaround is to run `npm rebuild blitz`.

Issue is that we create a `node_modules/next` to `node_modules/@blitzjs/next` symlink and that is apparently getting deleted.

**Comment by flybayer** [comment]
Published a fix in https://github.com/blitz-js/blitz/releases/tag/v0.34.0-canary.3

Let me know if that doesn't solve the problem

**Comment by mbrookson** [comment]
This just happened randomly to me after installing some other dependencies. 0.34.0-canary resolves it though. Thanks!

**Comment by flybayer** [comment]
For anyone else who may encounter this, it seems there's a bug in npm v6 that causes this error in 0.34.x releases. Upgrading to node 14+ (npm v7) resolves the issue.
