### ISSUE TITLE
Allow suspense but not concurrent mode

### ISSUE THREAD

**Issue by lcswillems** [blitz-js/blitz#1958]
### What is the problem?

With Blitz 0.29.7, I encountered an issue when using Chakra-UI and @anteprimorac said me to add this to `blitz.config.js`:

```
experimental: {
   reactMode: "legacy",
}
```

what I did. It fixed the issue while still allowing me to use Suspense. However, after the upgrade to 0.30, it seems that I can't use suspense anymore in legacy mode.

**Comment by flybayer** [comment]
@lcswillems that's an odd one, I can't think of anything that changed around this.

Can you provide more details, logs, etc?

Also a reproduction codesandbox or repo would really help

**Comment by lcswillems** [comment]
Okay! I will do it

**Comment by lcswillems** [comment]
Here is the reproduction:

- In Blitz 0.29.7, Suspense works with legacy reactMode: https://codesandbox.io/s/blitz-030-with-bug-forked-6bkiz
- In Blitz 0.30.2, Suspense doesn't work with legacy reactMode: https://codesandbox.io/s/blitz-030-with-bug-1uu3j

The only difference is Blitz version.

**Comment by flybayer** [comment]
Thank you, that's very helpful! I see the main issue is this in browser console.

```
Error was not caught TypeError: Object(...) is not a function
    at _getBlitzRuntimeData (core.esm.js?d9d4:436)
    at getBlitzRuntimeData (core.esm.js?d9d4:447)
```

**Comment by lcswillems** [comment]
Thank you for your support!!

**Comment by flybayer** [comment]
So that error is because with `0.30.x` you must have a custom `_document.tsx` page as follows:
```tsx
import {Document, Html, DocumentHead, Main, BlitzScript /*DocumentContext*/} from 'blitz'

class MyDocument extends Document {
  // Only uncomment if you need to customize this behaviour
  // static async getInitialProps(ctx: DocumentContext) {
  //   const initialProps = await Document.getInitialProps(ctx)
  //   return {...initialProps}
  // }

  render() {
    return (
      <Html lang="en">
        <DocumentHead />
        <body>
          <Main />
          <BlitzScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

That will get what you want. However, `blitz build` still fails with a React error: https://reactjs.org/docs/error-decoder.html/?invariant=294

Because suspense for data fetching is still experimental. So officially we do not support suspense in legacy mode.

As for the issue with chakra-ui, there's an upcoming react experimental release that should fix that.

**Comment by lcswillems** [comment]
Adding or removing the custom page `_document.tsx` doesn't change anything to the issue.

0.29.7 and 0.30.0 both use the same experimental version of React.

So I don't understand what I should conclude from your message: where had been the bug introduced in Blitz? Because it is not coming from neither React (that has not changed) or my app (adding `_document.tsx` solves nothing).

**Comment by flybayer** [comment]
@lcswillems ah, I'm so sorry, I forgot one key thing. `useQuery` now defaults to `{suspense: false}` if reactMode is legacy. So now you have to add `{suspense: true}` to `useQuery` third argument for it to work.

See https://codesandbox.io/s/blitz-030-with-bug-forked-ubcet?file=/app/pages/index.tsx

**Comment by lcswillems** [comment]
Thank you!! Is there a way to set it globally?

**Comment by flybayer** [comment]
No because, as I said, suspense without concurrent mode is not supported :)

**Comment by bacongravy** [comment]
@lcswillems While Suspense may appear to work in "legacy" mode during development, server-side rendering and client-side rehydration of Suspense does not[1], so in general, Suspense will not reliably work with Blitz in "legacy" mode, unless you ensure that your Suspense only ever gets rendered client-side.

You might try setting reactMode to "blocking" and see if that works for you; the issues you're seeing with Chakra UI might only occur in "concurrent" mode, and Blitz will default to having Suspense enabled.

[1] https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

**Comment by lcswillems** [comment]
THANKS A LOT @bacongravy !!

I have just put:

```
experimental: {
    reactMode: "blocking",
},
```

And I have Suspense working by default and no Chakra UI bug.

**Comment by flybayer** [comment]
Thanks @bacongravy! Do you think it would makes sense to set 'blocking' as default in Blitz instead of concurrent?

**Comment by flybayer** [comment]
Concurrent mode is now fixed for me as of react/react-dom `0.0.0-experimental-1fafac002` with react-final-form, so very likely Chakra is fixed too!
